steps:

- name: "gcr.io/cloud-builders/gcloud"
  args: ['iam', 'service-accounts', 'keys', 'create', 'credentials.json', '--iam-account=next-tokyo-taxi@$PROJECT_ID.iam.gserviceaccount.com', '--key-file-type=json']

- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/pubsub-emulator:latest", "--build-arg", "PROJECT_ID=$PROJECT_ID", "."]

images:
- "gcr.io/$PROJECT_ID/pubsub-emulator:latest"